### ISSUE TITLE
self::removeToken()

### ISSUE THREAD

**Issue by nkforeg** [banujan6/CSRF-handler#17]
Is it necessary add **self::removeToken()** in checkToken()?
I submit form via ajax, the first time is true but false in second because token was removed.

**Comment by banujan6** [comment]
Hello @nkforeg 

Yes, because the token should be used once, Then we should invalidate them. If you are making an ajax request, You should generate a new token for every request.

However, I recommend you not to use this package anymore since we no longer maintain it. Please consider using frameworks that come with a lot of security enhancements by default.
